### ISSUE TITLE
Plugin removes fragment from redirected long URL

### ISSUE THREAD

**Issue by dgw** [katzwebservices/google-analytics-for-yourls#13]
It seems this plugin, at least under YOURLS 1.7.1, is removing the fragment from the long URL before the redirect is sent. See YOURLS/YOURLS#2121 and YOURLS/YOURLS#2142 for confirmation from users that disabling this plugin restores normal YOURLS behavior.

Note: I tried to comment on #11 initially, but no matter what GitHub wouldn't let me; it just said "You can't comment at this time." Apologies for the duplicate, but this was the only way I could find to actually confirm the outstanding issue even though there's already an open ticket covering it.

**Comment by dgw** [comment]
Figured out why I couldn't comment (somewhat obscure browser extension issue). Closed as duplicate of #11.

**Comment by TablesawTablesawsen** [comment]
Thank you for this response, as it helped solve a similar problem I was having.
