### ISSUE TITLE
Should this plugin be removed from the YOURLS plugin list?

### ISSUE THREAD

**Issue by ozh** [katzwebservices/google-analytics-for-yourls#8]
Hi @zackkatz, there are a couple issues about your plugin being broken and seemingly abandonned. If so, no sweat, but just give us a ping so we can safely remove the plugin from the YOURLS plugin list.

Thanks,
Ozh

**Comment by sirtet** [comment]
If there will be no answer or Yes, i'd suggest to fork it under a new name, if someone does so:

1. This module is on it's homepage appropriately called _Google Analytics Link Tagging_, as it's used to tag the long URL's.
  But for some reason, here (and in it's code) it's named _google-analytics-for-yourls_
2. On the plugins-list, https://github.com/YOURLS/YOURLS/wiki/Plugin-List
there is another plugin called _Google Analytics for YOURLS_ which adds analytics code to YOURLS.

**Comment by zackkatz** [comment]
@ozh I *want* to fix it, it's just finding the time! @sirtet if you'd like to help contribute, that'd be great!

**Comment by zackkatz** [comment]
@ozh Thanks to @ifnull and @sirtet, it's now working with 1.7.

**Comment by ozh** [comment]
:+1: !
